- name: Pull PostgreSQL Docker image
  docker_image:
    name: postgres
    source: pull

- name: Create custom Docker network
  docker_network:
    name: movie_app_network
    driver: bridge
    state: present

- name: Create PostgreSQL container
  docker_container:
    name: db
    image: postgres
    state: started
    restart_policy: always
    exposed_ports:
      - "5432"
    published_ports:
      - "5432:5432"
    env:
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ db_password }}"
      POSTGRES_DB: "{{ db_name }}"
    networks:
      - name: movie_app_network
    volumes:
      - "/home/devops/movie-app/init-db:/docker-entrypoint-initdb.d"

