- name: Deploy Movie App with PostgreSQL
  hosts: web
  become: yes
  vars_files:
    - vault/db_password.yml
    - vault/sudo_password.yml
  vars:
    db_host: "db"
  roles:
    - docker
    - db-docker
    - web-cr
    - nginx

