- name: Copy movie app to the remote server
  ansible.builtin.copy:
    src: "../movie-app/" 
    dest: "/home/devops/movie-app/" 
    remote_src: no
    owner: devops
    group: devops
    mode: '0755'


- name: Build Docker image for movie app
  docker_image:
    name: movie-app
    tag: latest
    state: present
    source: build
    build:
      path: "/home/devops/movie-app"  

- name: Create custom Docker network
  docker_network:
    name: movie_app_network
    driver: bridge
    state: present

- name: Run movie app container
  docker_container:
    name: movie-app
    image: movie-app:latest
    state: started
    restart_policy: always
    ports:
      - "3000:3000"
    env:
      DATABASE_URL: "postgres://{{ db_user }}:{{ db_password }}@{{ db_host }}:5432/{{ db_name }}"
    networks:
      - name: movie_app_network
    etc_hosts:
      host.docker.internal: "host-gateway"  

